### ISSUE TITLE
Could not get session properties. Error: TooManyRequests;

### ISSUE THREAD

**Issue by WikkidEdd** [Azure/azure-remote-rendering#69] opened 2022-03-31 14:31 UTC
We saw an error we've not seen before today:

`Could not get session properties. Error: TooManyRequests; Message:`

It was during a session with a client. 2 users appeared to connect to the session, but then shortly after received this error.

Can you explain what is going on here? Is this something we're doing wrong? As far as I know, that call to get session properties is internal to the SDK.

Here are the session ids:
2e5d3fc4-4557-4294-b396-d32f43b6f94d
888dc705-478e-4f76-80fc-d65cd92fd9d9

As a side note, we've had the TooManyRequests error before when polling the conversion status too frequently, but never with the client. What is the criteria for the TooManyRequest, is it too many total for the server or too many from a partiular IP address or something else?

**Comment by ChristopherManthei** [comment] 2022-03-31 18:27
Hi @WikkidEdd ,
sorry for the inconvenience caused by this. There is definitely a bug on our side. If we query the session status during connect we don't account for the delay to the previous get session status call that detected the VM to be ready. However, we need to do some further investigations here so we will get back to you soon. 
Cheers,
Christopher

**Comment by ChristopherManthei** [comment] 2022-04-05 16:01
Hi again @WikkidEdd ,
We will be increasing the throttling threshold to account for the increased request frequency when polling for a standard VM. Additionally we will change our code to retry on TooManyRequests during connect.
Regarding your question: throttling is done individually for each region and request path. So requests in one region will not affect throttling in another region and requests to for example "Get Session" will not affect other requests to "Create Session" etc.
We will update the ticket as soon as the changes go live.
Cheers,
Christopher

**Comment by WikkidEdd** [comment] 2022-04-06 10:33
Thanks for the update.

Does that imply that if other users of ARR in the same region are making requests at a too high frequency it could cause our request to fail?

**Comment by ChristopherManthei** [comment] 2022-04-06 10:36
No each ARR account is treated individually. Accounts cannot affect each other.

**Comment by WikkidEdd** [comment] 2022-04-06 10:38
Ah, I should also clarify that when the users experienced the TooManyRequests error. It wasn't during connect, it was mid-session and the session continued afterward. We only knew about it because our error handling takes any error via OnSessionErrorEncountered to be fatal and showed an error to the user.

**Comment by ChristopherManthei** [comment] 2022-04-06 15:09
Thank you for the clarification. This is clearly an oversight on our part in the auto-renew session code. We will look into it.

**Closed** 2022-04-28 15:58 UTC
