### ISSUE TITLE
[Remote rendering problem] Unable to set Storage Account Settings

### ISSUE THREAD

**Issue by florolf1** [Azure/azure-remote-rendering#6] opened 2020-05-19 12:05 UTC
**Describe the problem**
Storage Account Settings ( MixedRealityToolkit->RemoteRenderingService ) are not saved after building the project.
Starting the App inside Unity Editor, it works fine and all my converted models are shown. After building the app, only the custom build-in model is shown.
Session connection is working fine.

**Additional context**
One week ago everything worked fine and i was able to load my custom models inside my storage.

**Setup**
com.microsoft.azur.remote-rendering: 0.1.30
com.microsoft.msbuildforunity: 0.8.4
Unity-Version: 2019.3

**already tried out**
- Downgrade remote-render package to 0.1.28
- Delete project and stated from scratch
- Building Project from other PC
- Delete VS and reinstalled
- Used other Unity version 2018.4 LST
- Used arr.account.xml in StreamingAssets Folder instead of a custom configuration profile

**Comment by janekvap** [comment] 2020-05-20 16:22
Hello Florian, thank you for reporting the issue, we are investigating it now and will come back as soon as we have any details on it.

**Comment by florolf1** [comment] 2020-05-22 07:07
Hello,
I can't confirm that. I have just tried it with a configuration profile and an arr.account.xml file and waited between 5-10 min. I was not able to see my custom models.
Package: 0.1.30

**Comment by janekvap** [comment] 2020-05-22 07:31
Can you try using arr.overrides.xml as instructed [here](https://github.com/Azure/azure-remote-rendering/blob/master/Unity/AzureRemoteRenderingShowcase/.documents/app-usage.md#configuration-profile). 
Could you also try to find out if the storage account data is set on the device or not? 
Build the sample with script debugging enabled:
![Unity_Fs6WA7i0ut](https://user-images.githubusercontent.com/56117111/82642508-52273d80-9c0e-11ea-88da-7e4260b95dec.jpg)
Put breakpoint in [RemoteRenderingService.cs line 817](https://github.com/Azure/azure-remote-rendering/blob/8bdadffdebab9e34d051bb2748f491f619c0c915/Unity/AzureRemoteRenderingShowcase/arr-showcase-app/Assets/App/Services/RemoteRenderingService.cs#L817) and attach Unity debugger with the C# unity solution (note the device has to be unplugged from PC), you can check the used storage account and key there.
This will help us see if we are reproducing the same issue or not.

**Comment by florolf1** [comment] 2020-05-22 09:32
I have now tested the sample project with configuration profile, arr.account.xml and acc.override.xml, started a session and waited several minutes without success.

For some reason i am not able to attach unity debugger to my build. Maybe because i am developing on Mac and i am using Parallel Desktop.
I followed these [instructions](https://docs.microsoft.com/en-us/windows/mixed-reality/managed-debugging-with-unity-il2cpp).
As under point 10) i see my device and attached the debugger to it, but it does not stop on any breakpoint.
So i put Debug.Log Messages inside the Initialize-Method of RemoteRenderingService.cs Script. Normally i am able to see the see the Debug.Log messages in the output window, but i dont see any output at all...
I'm gonna try it again right now. I'm sorry I can't help with that.

**Comment by janekvap** [comment] 2020-05-22 11:41
You can try to close the app and through Device Portal go to  User Folders\LocalAppData\<your app>\TempState\UnityPlayer.log
Check the log for errors / log messages.

**Comment by florolf1** [comment] 2020-05-22 12:07
Got it. Thank you.
My storage account data is set on the device.
In the following a small excerpt from the log.
I can also provide you with the complete log if it helps.

.
.
.
Shader 'BlobWireFrame': fallback shader 'Unlit' not found
UnloadTime: 1,472448 ms
Unable to register IMixedRealityInputDeviceManager service with a null concrete type.
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
Microsoft.MixedReality.Toolkit.BaseDataProviderAccessCoreSystem:RegisterDataProviderInternal(Boolean, Type, SupportedPlatforms, Object[])
Microsoft.MixedReality.Toolkit.BaseDataProviderAccessCoreSystem:RegisterDataProvider(Type, SupportedPlatforms, Object[])
Microsoft.MixedReality.Toolkit.Input.MixedRealityInputSystem:CreateDataProviders()
Microsoft.MixedReality.Toolkit.Input.MixedRealityInputSystem:Initialize()
Microsoft.MixedReality.Toolkit.<>c:<InitializeAllServices>b__60_0(IMixedRealityService)
System.Action`1:Invoke(T)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:ExecuteOnAllServices(IEnumerable`1, Action`1)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:ExecuteOnAllServicesInOrder(Action`1)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:InitializeAllServices()
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:InitializeServiceLocator()
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:InitializeInstance()
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:RegisterInstance(MixedRealityToolkit, Boolean)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:Awake()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Failed to load data from account file 'ms-appx:///Data/StreamingAssets/arr.account.xml'. Reason: Unable to find the specified file. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)
.
.
.

**Comment by janekvap** [comment] 2020-05-26 16:19
Sorry, we are still not able to reproduce here.
"Failed to load container data. Reason: An error occurred while sending the request"
This line says the http request to Azure Storage to enumerate the models failed but isn't very helpful.
Can you try changing [this line](https://github.com/Azure/azure-remote-rendering/blob/8bdadffdebab9e34d051bb2748f491f619c0c915/Unity/AzureRemoteRenderingShowcase/arr-showcase-app/Assets/App/Services/RemoteRenderingService.cs#L878) to:
`Debug.LogFormat(LogType.Error, LogOption.NoStacktrace, null, "{0}",  $"Failed to load container data. Reason: {ex.Message} Detail: {ex.InnerException?.Message}");`
This should provide more information in the log about what went wrong.

**Comment by florolf1** [comment] 2020-05-27 06:56
This is the output after changing the line .

Failed to load container data. Reason: An error occurred while sending the request Detail: Error: ConnectFailure (Value does not fall within the expected range.)

**Comment by janekvap** [comment] 2020-05-28 19:40
Currently we think the issue is outside our codebase - device environment (updates, other sw on device...) and would like to see if minimal application doing this HttpClient call succeeds or not.
We are out for long weekend but can provide a sample next week.

**Comment by florolf1** [comment] 2020-05-29 11:41
I don't get it. Last week everything was working fine. 
I have now reset the device to the factory default and made a fresh installation. I still does not show my custom models on device.

**Comment by florolf1** [comment] 2020-06-04 08:47
Hi, 
the same thing happens as before. Inside Unity i can see the list of models. On device, i can only see the debug panel.
UnityPlayer.log

Failed to load container data. Reason: An error occurred while sending the request Detail:System.Net.WebException: Error: ConnectFailure (Value does not fall within the expected range.) ---> System.ArgumentException: Value does not fall within the expected range.
  at System.Net.Sockets.Socket.SetSocketOption (System.Net.Sockets.SocketOptionLevel optionLevel, System.Net.Sockets.SocketOptionName optionName, System.Int32 optionValue) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Net.Sockets.Socket.SocketDefaults () [0x00000] in <00000000000000000000000000000000>:0 
  at System.Net.Sockets.Socket..ctor (System.Net.Sockets.AddressFamily addressFamily, System.Net.Sockets.SocketType socketType, System.Net.Sockets.ProtocolType protocolType) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Net.WebConnection.InitConnection (System.Net.HttpWebRequest request) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Net.WebConnection.<SendRequest>b__41_0 (System.Object o) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading.SendOrPostCallback.Invoke (System.Object state) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context (System.Object state) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading.SendOrPostCallback.Invoke (System.Object state) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in <00000000000000000000000000000000>:0 
   --- End of inner exception stack trace ---
  at System.Net.HttpWebRequest.EndGetResponse (System.IAsyncResult asyncResult) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Converter`2[TInput,TOutput].Invoke (TInput input) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading.Tasks.TaskFactory`1+<>c__DisplayClass35_1[TResult].<FromAsyncImpl>b__1 (System.IAsyncResult iar) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.Camera+CameraCallback.Invoke (UnityEngine.Camera cam) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.Windows.WebCam.VideoCapture+OnVideoCaptureResourceCreatedCallback.Invoke (UnityEngine.Windows.WebCam.VideoCapture captureObject) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Net.SimpleAsyncResult.SetCompleted (System.Boolean synch, System.Exception e) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Net.HttpWebRequest.SetWriteStreamError (System.Net.WebExceptionStatus status, System.Exception exc) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Net.WebConnection.InitConnection (System.Net.HttpWebRequest request) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Net.WebConnection.<SendRequest>b__41_0 (System.Object o) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading.SendOrPostCallback.Invoke (System.Object state) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context (System.Object state) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading.SendOrPostCallback.Invoke (System.Object state) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in <00000000000000000000000000000000>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <00000000000000000000000000000000>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Runtime.CompilerServices.ConditionalWeakTable`2[TKey,TValue]..ctor () [0x00000] in <00000000000000000000000000000000>:0 
  at <PrivateImplementationDetails>.ComputeStringHash (System.String s) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext (System.Object stateMachine) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading.SendOrPostCallback.Invoke (System.Object state) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run () [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading.ThreadStart.Invoke () [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction (System.Action action, System.Boolean allowInlining, System.Threading.Tasks.Task& currentTask) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading.Tasks.Task.FinishContinuations () [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading.Tasks.Task.FinishStageTwo () [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading.Tasks.Task.Finish (System.Boolean bUserDelegateExecuted) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading.Tasks.Task`1[TResult].TrySetException (System.Object exceptionObject) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading.Tasks.UnwrapPromise`1[TResult].TrySetFromTask (System.Threading.Tasks.Task task, System.Boolean lookForOce) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading.Tasks.UnwrapPromise`1[TResult].InvokeCore (System.Threading.Tasks.Task completingTask) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading.Tasks.UnwrapPromise`1[TResult].Invoke (System.Threading.Tasks.Task completingTask) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading.Tasks.Task.FinishContinuations () [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading.Tasks.Task.FinishStageTwo () [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading.Tasks.Task.Finish (System.Boolean bUserDelegateExecuted) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading.Tasks.Task`1[TResult].TrySetException (System.Object exceptionObject) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading.Tasks.TaskFactory`1+<>c__DisplayClass35_1[TResult].<FromAsyncImpl>b__1 (System.IAsyncResult iar) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.Camera+CameraCallback.Invoke (UnityEngine.Camera cam) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.Windows.WebCam.VideoCapture+OnVideoCaptureResourceCreatedCallback.Invoke (UnityEngine.Windows.WebCam.VideoCapture captureObject) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Net.SimpleAsyncResult.SetCompleted (System.Boolean synch, System.Exception e) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Net.HttpWebRequest.SetWriteStreamError (System.Net.WebExceptionStatus status, System.Exception exc) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Net.WebConnection.InitConnection (System.Net.HttpWebRequest request) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Net.WebConnection.<SendRequest>b__41_0 (System.Object o) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading.SendOrPostCallback.Invoke (System.Object state) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context (System.Object state) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading.SendOrPostCallback.Invoke (System.Object state) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in <00000000000000000000000000000000>:0

**Comment by gringlas** [comment] 2020-06-04 14:55
I'm having a similiar problem with System.Net.Http.HttpClient and Marc Applesmeier pointed me on this topic in the mixedreality slug. In my case I'm just trying to do a bunch of requests, which worked perfectly well, but when trying to do an update some days ago I always recieve a WebRequestException when I run the app on our HoloLens 1 device with Status Code 2 and this message: 
`Failed to load container data. Reason: An error occurred while sending the request Detail:System.Net.WebException: Error: ConnectFailure (Value does not fall within the expected range.) ---> System.ArgumentException: Value does not fall within the expected range.`

In Unity and in an older version I still have installed on the device  everything is running as it should.

**Comment by janekvap** [comment] 2020-06-04 15:14
Since Florian tried older Unity version it doesn't seem to be Unity issue.
Which Visual Studio version are you using to compile the project? I am still on 16.5.4 from April 26. and the HttpClient works. Updating to latest now to check.

**Comment by gringlas** [comment] 2020-06-05 05:34
In my case I still have an older working version of my app, which was built with  Microsoft Visual Studio Community 2017 Version 15.5.2 at my home - could try that out again later. On my work computer I have tried building the app with Visual Studio 2017 (15.9.23) and Visual Studio 2019 (16.6.1), but the httpclient won't connect if I built the solution from one of those.

**Comment by florolf1** [comment] 2020-06-05 11:55
I am using VS 16.6.1.
I tried it on another PC (VS 16.5.4) without success. The same error occurs.

**Comment by janekvap** [comment] 2020-06-05 12:43
So VS also doesn't seem to be the culprit, can I also ask you for your PC Windows version/OS build number? Are you on any Insider program? I am going to check what the il2cpp generates for those HttpClient calls to see if we can log issue to Unity/ VS/ Windows.

**Comment by gringlas** [comment] 2020-06-06 09:34
I'm running on Windows 10 Pro Version 1903 and I'm not in any Insider program.
I have also stated my problem in the unity forums https://forum.unity.com/threads/hololens-1-httpclient-connect-failure.905039/ and someone there stated that he has the exact same problems with Unity2019.3.1

**Comment by florolf1** [comment] 2020-06-08 08:11
Building the app with Unity Version 2019.3.15f1 and VS 16.6.1 is working for me. No more Http Errors occur and i can see my custom models.
I also tryed building the app with Unity Version 2019.3.13f1 and 2019.3.11f1 with VS 16.6.1. and i am getting the Http Error. 
For some reason with Unity version 2018.4 LST and VS 16.6.1 it is working as well now, but it did not work 3 weeks ago. Maybe that was my fault...

**Comment by janekvap** [comment] 2020-06-08 08:46
If all is working now I will close the issue. Sorry for the hiccup in your fun times with HL2 and ARR. 
It seems that Unity version (maybe in combination with OS update) caused this issue and is **resolved by updating to Unity 2019.3.15f1+.**

**Closed by janekvap** 2020-06-08 08:46 UTC
