### ISSUE TITLE
[Remote rendering problem] Native Cpp Not working

### ISSUE THREAD

**Issue by werto165** [Azure/azure-remote-rendering#8] opened 2020-06-04 10:03 UTC
**Describe the problem**

I have altered the account keys, account ID and domain to the correct domains and put in my assets SAS URL. Yesterday I was able to get an active rendering session show up on the azure dashboard(it didn't work), however today I'm not even getting a active rendering session show up on the dashboard. I am getting an exception thrown at `Exception thrown at 0x00007FF7D38A6598 in HolographicApp.exe: 0xC0000005: Access violation writing location 0x00007FF8E5EBF7D0.` 

I am using the hololens 2 and visual studio 2019 however, I have left the project in VS2017 v141 toolset. ARM64 and release mode. 

**Provide additional information**

```Exception thrown at 0x00007FF90A1939EC (KernelBase.dll) in HolographicApp.exe: WinRT originate error - 0x80040111 : 'ClassFactory cannot supply requested class'.
Exception thrown at 0x00007FF90A1939EC in HolographicApp.exe: Microsoft C++ exception: winrt::hresult_class_not_available at memory location 0x000000AB355FCFE8.
Exception thrown at 0x00007FF90A1939EC in HolographicApp.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
Exception thrown at 0x00007FF90A1939EC (KernelBase.dll) in HolographicApp.exe: 0x40080202: WinRT transform error (parameters: 0x0000000080040111, 0x0000000000000000, 0x0000000000000027, 0x000000AB355FCC10).
Exception thrown at 0x00007FF90A1939EC (KernelBase.dll) in HolographicApp.exe: WinRT originate error - 0x80040111 : 'ClassFactory cannot supply requested class'.
Exception thrown at 0x00007FF90A1939EC in HolographicApp.exe: Microsoft C++ exception: winrt::hresult_class_not_available at memory location 0x000000AB355FCD68.
Exception thrown at 0x00007FF90A1939EC in HolographicApp.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
Exception thrown at 0x00007FF90A1939EC (KernelBase.dll) in HolographicApp.exe: 0x40080202: WinRT transform error (parameters: 0x0000000080040111, 0x0000000000000000, 0x0000000000000027, 0x000000AB355FC990).
'HolographicApp.exe' (Win32): Loaded 'C:\Windows\system32\PerceptionDevice.dll'. 
'HolographicApp.exe' (Win32): Loaded 'B:\Windows\System32\DriverStore\FileRepository\qcdx_ffu850.inf_arm64_3f3ec3a0cb26c5d1\qcdx11arm64um850.dll'. 
'HolographicApp.exe' (Win32): Loaded 'C:\Windows\system32\forwarders\advapi32.dll'. 
'HolographicApp.exe' (Win32): Loaded 'C:\Windows\system32\FWPUCLNT.DLL'. 
'HolographicApp.exe' (Win32): Loaded 'B:\Windows\System32\DriverStore\FileRepository\qcdx_ffu850.inf_arm64_3f3ec3a0cb26c5d1\qcdxarm64compiler850.DLL'. 
Exception thrown at 0x00007FF90A1939EC (KernelBase.dll) in HolographicApp.exe: WinRT originate error - 0x80040111 : 'ClassFactory cannot supply requested class'.
Exception thrown at 0x00007FF90A1939EC in HolographicApp.exe: Microsoft C++ exception: winrt::hresult_class_not_available at memory location 0x000000AB355FD1D8.
Exception thrown at 0x00007FF90A1939EC in HolographicApp.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
Exception thrown at 0x00007FF90A1939EC (KernelBase.dll) in HolographicApp.exe: 0x40080202: WinRT transform error (parameters: 0x0000000080040111, 0x0000000000000000, 0x0000000000000027, 0x000000AB355FCE00).
'HolographicApp.exe' (Win32): Loaded 'C:\Windows\system32\Windows.StateRepositoryClient.dll'. 
'HolographicApp.exe' (Win32): Loaded 'C:\Windows\system32\schannel.dll'. 
'HolographicApp.exe' (Win32): Loaded 'C:\Windows\system32\TextShaping.dll'. 
'HolographicApp.exe' (Win32): Loaded 'C:\Windows\system32\BCP47mrm.dll'. 
Exception thrown at 0x00007FF90A1939EC (KernelBase.dll) in HolographicApp.exe: WinRT originate error - 0x80040111 : 'ClassFactory cannot supply requested class'.
Exception thrown at 0x00007FF90A1939EC in HolographicApp.exe: Microsoft C++ exception: winrt::hresult_class_not_available at memory location 0x000000AB355FECF8.
Exception thrown at 0x00007FF90A1939EC in HolographicApp.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
Exception thrown at 0x00007FF90A1939EC (KernelBase.dll) in HolographicApp.exe: 0x40080202: WinRT transform error (parameters: 0x0000000080040111, 0x0000000000000000, 0x0000000000000027, 0x000000AB355FE920).
'HolographicApp.exe' (Win32): Loaded 'C:\Windows\system32\mskeyprotect.dll'. 
'HolographicApp.exe' (Win32): Loaded 'C:\Windows\system32\ntasn1.dll'. 
'HolographicApp.exe' (Win32): Loaded 'C:\Windows\system32\ncrypt.dll'. 
'HolographicApp.exe' (Win32): Loaded 'C:\Windows\system32\ncryptsslp.dll'. 
'HolographicApp.exe' (Win32): Loaded 'C:\Windows\system32\cryptnet.dll'. 
Exception thrown at 0x00007FF90A1939EC (KernelBase.dll) in HolographicApp.exe: WinRT originate error - 0x80040111 : 'ClassFactory cannot supply requested class'.
Exception thrown at 0x00007FF90A1939EC in HolographicApp.exe: Microsoft C++ exception: winrt::hresult_class_not_available at memory location 0x000000AB355FE348.
Exception thrown at 0x00007FF90A1939EC in HolographicApp.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
Exception thrown at 0x00007FF90A1939EC (KernelBase.dll) in HolographicApp.exe: 0x40080202: WinRT transform error (parameters: 0x0000000080040111, 0x0000000000000000, 0x0000000000000027, 0x000000AB355FDF70).
Exception thrown at 0x00007FF7D38A6598 in HolographicApp.exe: 0xC0000005: Access violation writing location 0x00007FF8E5EBF7D0.
```

If you have them, please provide either or both of the following:
* The sessionId (See [here](https://docs.microsoft.com/en-us/azure/remote-rendering/how-tos/session-rest-api#example-script-store-sessionid))
* An MS-CV code (See [here](https://docs.microsoft.com/en-us/azure/remote-rendering/how-tos/session-rest-api#common-response-headers))

**Additional context**

**Comment by werto165** [comment] 2020-06-04 13:08
I have tried with a directx11 sample holographic application copying and pasting the relevant areas of code and it seems like I am getting similar results with WinRT originate error. And another error: 

D3D11 WARNING: ID3D11DeviceContext::DrawIndexedInstanced: There are no viewports currently bound.


Exception thrown at 0x00007FFDED4339EC (KernelBase.dll) in AzureRemoteRenderingTesting.exe: WinRT originate error - 0x80040111 : 'ClassFactory cannot supply requested class'.
Exception thrown at 0x00007FFDED4339EC in AzureRemoteRenderingTesting.exe: Microsoft C++ exception: winrt::hresult_class_not_available at memory location 0x000000F9EA7FCC68.
Exception thrown at 0x00007FFDED4339EC in AzureRemoteRenderingTesting.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
Exception thrown at 0x00007FFDED4339EC (KernelBase.dll) in AzureRemoteRenderingTesting.exe: 0x40080202: WinRT transform error (parameters: 0x0000000080040111, 0x0000000000000000, 0x0000000000000027, 0x000000F9EA7FC890).
Exception thrown at 0x00007FFDED4339EC (KernelBase.dll) in AzureRemoteRenderingTesting.exe: WinRT originate error - 0x80040111 : 'ClassFactory cannot supply requested class'.
Exception thrown at 0x00007FFDED4339EC in AzureRemoteRenderingTesting.exe: Microsoft C++ exception: winrt::hresult_class_not_available at memory location 0x000000F9EA7FC9E8.
Exception thrown at 0x00007FFDED4339EC in AzureRemoteRenderingTesting.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
Exception thrown at 0x00007FFDED4339EC (KernelBase.dll) in AzureRemoteRenderingTesting.exe: 0x40080202: WinRT transform error (parameters: 0x0000000080040111, 0x0000000000000000, 0x0000000000000027, 0x000000F9EA7FC610).
'AzureRemoteRenderingTesting.exe' (Win32): Loaded 'C:\Windows\system32\PerceptionDevice.dll'. 
'AzureRemoteRenderingTesting.exe' (Win32): Loaded 'C:\Windows\system32\DXGIDebug.dll'. 
'AzureRemoteRenderingTesting.exe' (Win32): Loaded 'C:\Windows\system32\d3d11_3SDKLayers.dll'. 
'AzureRemoteRenderingTesting.exe' (Win32): Unloaded 'C:\Windows\system32\d3d11_3SDKLayers.dll'
'AzureRemoteRenderingTesting.exe' (Win32): Loaded 'B:\Windows\System32\DriverStore\FileRepository\qcdx_ffu850.inf_arm64_3f3ec3a0cb26c5d1\qcdx11arm64um850.dll'. 
'AzureRemoteRenderingTesting.exe' (Win32): Loaded 'C:\Windows\system32\forwarders\advapi32.dll'. 
'AzureRemoteRenderingTesting.exe' (Win32): Loaded 'C:\Windows\system32\d3d11_3SDKLayers.dll'. 
'AzureRemoteRenderingTesting.exe' (Win32): Loaded 'B:\Windows\System32\DriverStore\FileRepository\qcdx_ffu850.inf_arm64_3f3ec3a0cb26c5d1\qcdxarm64compiler850.DLL'. 
Exception thrown at 0x00007FFDED4339EC (KernelBase.dll) in AzureRemoteRenderingTesting.exe: WinRT originate error - 0x80040111 : 'ClassFactory cannot supply requested class'.
Exception thrown at 0x00007FFDED4339EC in AzureRemoteRenderingTesting.exe: Microsoft C++ exception: winrt::hresult_class_not_available at memory location 0x000000F9EA7FCD18.
Exception thrown at 0x00007FFDED4339EC in AzureRemoteRenderingTesting.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
Exception thrown at 0x00007FFDED4339EC (KernelBase.dll) in AzureRemoteRenderingTesting.exe: 0x40080202: WinRT transform error (parameters: 0x0000000080040111, 0x0000000000000000, 0x0000000000000027, 0x000000F9EA7FC940).
'AzureRemoteRenderingTesting.exe' (Win32): Loaded 'C:\Windows\system32\Windows.StateRepositoryClient.dll'. 
'AzureRemoteRenderingTesting.exe' (Win32): Loaded 'C:\Windows\system32\BCP47mrm.dll'. 
Exception thrown at 0x00007FFDED4339EC (KernelBase.dll) in AzureRemoteRenderingTesting.exe: WinRT originate error - 0x80040111 : 'ClassFactory cannot supply requested class'.
Exception thrown at 0x00007FFDED4339EC in AzureRemoteRenderingTesting.exe: Microsoft C++ exception: winrt::hresult_class_not_available at memory location 0x000000F9EA7FE8F8.
Exception thrown at 0x00007FFDED4339EC in AzureRemoteRenderingTesting.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
Exception thrown at 0x00007FFDED4339EC (KernelBase.dll) in AzureRemoteRenderingTesting.exe: 0x40080202: WinRT transform error (parameters: 0x0000000080040111, 0x0000000000000000, 0x0000000000000027, 0x000000F9EA7FE520).
D3D11 WARNING: ID3D11DeviceContext::DrawIndexedInstanced: There are no viewports currently bound.  If any rasterization to RenderTarget(s) and/or DepthStencil is performed, results will be undefined. [ EXECUTION WARNING #384: DEVICE_DRAW_VIEWPORT_NOT_SET]
Exception thrown at 0x00007FFDED4339EC (KernelBase.dll) in AzureRemoteRenderingTesting.exe: WinRT originate error - 0x80040111 : 'ClassFactory cannot supply requested class'.
Exception thrown at 0x00007FFDED4339EC in AzureRemoteRenderingTesting.exe: Microsoft C++ exception: winrt::hresult_class_not_available at memory location 0x000000F9EA7FDC28.
Exception thrown at 0x00007FFDED4339EC in AzureRemoteRenderingTesting.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
Exception thrown at 0x00007FFDED4339EC (KernelBase.dll) in AzureRemoteRenderingTesting.exe: 0x40080202: WinRT transform error (parameters: 0x0000000080040111, 0x0000000000000000, 0x0000000000000027, 0x000000F9EA7FD850).
D3D11 WARNING: ID3D11DeviceContext::DrawIndexedInstanced: There are no viewports currently bound.  If any rasterization to RenderTarget(s) and/or DepthStencil is performed, results will be undefined. [ EXECUTION WARNING #384: DEVICE_DRAW_VIEWPORT_NOT_SET]
D3D11 WARNING: ID3D11DeviceContext::DrawIndexedInstanced: There are no viewports currently bound.  If any rasterization to RenderTarget(s) and/or DepthStencil is performed, results will be undefined. [ EXECUTION WARNING #384: DEVICE_DRAW_VIEWPORT_NOT_SET]
Exception thrown at 0x00007FFDED4339EC (KernelBase.dll) in AzureRemoteRenderingTesting.exe: WinRT originate error - 0x80040111 : 'ClassFactory cannot supply requested class'.
Exception thrown at 0x00007FFDED4339EC in AzureRemoteRenderingTesting.exe: Microsoft C++ exception: winrt::hresult_class_not_available at memory location 0x000000F9EA7FD9E8.
Exception thrown at 0x00007FFDED4339EC in AzureRemoteRenderingTesting.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
Exception thrown at 0x00007FFDED4339EC (KernelBase.dll) in AzureRemoteRenderingTesting.exe: 0x40080202: WinRT transform error (parameters: 0x0000000080040111, 0x0000000000000000, 0x0000000000000027, 0x000000F9EA7FD610).

**Comment by FlorianBorn71** [comment] 2020-06-04 13:19
Hello and thanks for your report! 
We have identified a problem in the session creation logic of the native C++ sample. It tries to connect to the runtime while the session is still starting up. It is unfortunately not a single line fix, so this will be fixed with the next SDK update that will be released within the next days.

However, there is a code path in the HL sample that does work today: If you specify a valid session ID through this member:

        m_sessionOverride = ""; // If there is a valid session ID to re-use, put it here. Otherwise a new one is created

inside function HolographicAppMain::HolographicAppMain

To create a valid session using your local PC, you can use the powershell script **RenderingSession.ps1** which is in the repo as well. Note that you need to put in your credentials into the sibling file **arrconfig.json**. 
When you run the script, it will start a session (it may take a few minutes) and output the session ID to the powershell console. You can copy that ID and paste it into the m_sessionOverride member and then compile&deploy the sample again.
See also this chapter: https://docs.microsoft.com/azure/remote-rendering/samples/powershell-example-scripts

Sorry for the inconveneience!.
Florian

**Comment by werto165** [comment] 2020-06-04 13:28
Thank you for your time in explaining what is going wrong. I thought I was going barmy! Will the code from the sample be updated along with the sdk?

**Comment by FlorianBorn71** [comment] 2020-06-04 13:30
yes, the sample code will be fixed and part of the next SDK. If it was only a few lines of code, I would post it here, but it is actually more ;-)

**Comment by werto165** [comment] 2020-06-04 13:31
One more quick question, what is "clientInit.toolId = "<sample name goes here>";" I am unsure what the sample name is in this context.

**Comment by FlorianBorn71** [comment] 2020-06-04 13:43
You can ignore the toolId, it does not serve a specific purpose outside logging. However, it must not be empty.

**Comment by werto165** [comment] 2020-06-04 13:45
And now I'm running into a bad gateway issue on azure! today is going great! :D 

```
message":"The server for this session encountered an error: Long running operation failed with status 'BadGateway'.","sessionElapsedTime":"00:00:00","sessionHostname":null,"sessionId":"xxxx-xxx-xxxx--xxx","sessionIp":null,"sessionMaxLeaseTime":"01:00:00","sessionSize":"Standard","sessionStatus":"Error","teraflops":0.0
```

**Comment by FlorianBorn71** [comment] 2020-06-04 13:48
I have seen problem has been reported today as well and it is under investigation

**Comment by werto165** [comment] 2020-06-04 13:52
I think the universe is telling me to work on something else in the mean time. I've tried on eastus2 and westeurope if that helps at all. Cheers for the fast responses :)

**Comment by FlorianBorn71** [comment] 2020-06-04 13:54
hehe, yes, one of those days...
and yes, it seems to affect all regions if I'm not mistaken

**Comment by FlorianBorn71** [comment] 2020-06-04 15:51
fwiw, you can query the Azure status here:
https://status.azure.com/status

**Comment by werto165** [comment] 2020-06-04 16:33
Thanks I've managed to test it again after a meeting, it seems to create the VM just fine and it seems like I'm getting access to it through the app. I was just wondering from a rendering standpoint, if the mesh doesn't have any textures will it still show up? And does the rendered object show where the default cube is? When you do the tap gesture should the model move to the new default cube location? 

I have a feeling it is not showing anything because of this error: 

D3D11 WARNING: ID3D11DeviceContext::DrawIndexedInstanced: There are no viewports currently bound.  If any rasterization to RenderTarget(s) and/or DepthStencil is performed, results will be undefined. [ EXECUTION WARNING #384: DEVICE_DRAW_VIEWPORT_NOT_SET]


I seem to be getting these errors intermittently: Unhandled exception at 0x00007FFDC7168E88 (Microsoft.Holographic.HybridRemoting.dll) in HolographicApp.exe: 0xC0000005: Access violation reading location 0x0000000000000000.

**Comment by FlorianBorn71** [comment] 2020-06-04 18:21
Regarding your questions:
> I was just wondering from a rendering standpoint, if the mesh doesn't have any textures
> will it still show up? 
Yes, untextured objects are supported, they will just have plain color material as defined in the source material. But the built-in engine model has textures.

> And does the rendered object show where the default cube is? 
The loaded object will be right at your head position. In case of the default engine model, you are even slightly inside it. 

> When you do the tap gesture should the model move to the new default cube location?
There is currently no logic in the sample to move the object along with the cube, but that would be simple to add of course. The purpose of this sample is to show the fastest path to see something on device, so we purposely left away all other code.

> I have a feeling it is not showing anything because of this error:
Does it mean you are not seeing the engine model? Or are you testing with your own model?
What does the text panel say? Does it transition into connected state and then load the model (with percentage progress indication?)

> D3D11 WARNING: ID3D11DeviceContext::DrawIndexedInstanced
I think you can gracefully ignore that warning, but I will check with my colleagues.

> I seem to be getting these errors intermittently: Unhandled exception at 0x00007FFDC7168E88
Hmm, that should of course not happen. When is it triggered? Have you started from inside VisualStudio, so you have a callstack?

**Comment by werto165** [comment] 2020-06-05 09:59
Hi, I have started it within visual studio but I converted the sample to v142 so it might be an incompatibility on that front. However, I am getting a InvalidToken( 1500), result now from the Result enum class.

 I am using my own geometry but I have break points in the AzureRemoteRenderingTesting::AzureRemoteRenderingTestingMain::UpdateStatusText() function because the status display doesn't work when moving to v142 because the std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t> toWChar; is no longer supported in C++ 17 standard https://en.cppreference.com/w/cpp/locale/codecvt_utf8. 

I am unsure where these errors occur as it is a lot of stepping over into non available pdb files.

**Comment by FlorianBorn71** [comment] 2020-06-05 15:49
There is a new version of the sample online now. Would be worthwhile to check it out and go from there,,,

**Comment by werto165** [comment] 2020-06-08 09:14
> There is a new version of the sample online now. Would be worthwhile to check it out and go from there,,,

It is working now, I've setup a session within the application took about 250 seconds, slightly slower than setting one up on the desktop with powershell. But its working! cheers for the update. First time I ran it however, I still get this error: I seem to be getting these errors intermittently: Unhandled exception at 0x00007FFDC7168E88 (Microsoft.Holographic.HybridRemoting.dll) in HolographicApp.exe: 0xC0000005: Access violation reading location 0x0000000000000000. not sure why.

**Comment by FlorianBorn71** [comment] 2020-06-08 09:29
Glad to hear it works now!
I'll log a ticket for the intermittent nullptr crash for further investigation.

**Comment by FlorianBorn71** [comment] 2020-06-08 09:36
> Is it possible to scale the geometry that is being rendered at azure? The model I imported was huge!

There are basically two options:
- You can scale the asset at conversion time
- You can dynamically scale objects at runtime if you apply scaling to the root entity. When you call LoadModel, you can pass a parent entity (it is null in the C++ sample) and if that entity is already scaled, the model will appear scaled right after loading.

In your case, it sounds a bit like an asset problem, so I would rather do this at conversion time.
Here is how to apply scaling at conversion time:
https://docs.microsoft.com/en-us/azure/remote-rendering/how-tos/conversion/configure-model-conversion#geometry-parameters

Cheers,
Florian

**Comment by FlorianBorn71** [comment] 2020-06-08 09:38
> slightly slower than setting one up on the desktop

I have no explanation why that might be the case - it might be pure coincidence? We see quite a bit of variation for the bring-up times in general.

**Comment by werto165** [comment] 2020-06-08 09:44
> > Is it possible to scale the geometry that is being rendered at azure? The model I imported was huge!
> 
> There are basically two options:
> 
> * You can scale the asset at conversion time
> * You can dynamically scale objects at runtime if you apply scaling to the root entity. When you call LoadModel, you can pass a parent entity (it is null in the C++ sample) and if that entity is already scaled, the model will appear scaled right after loading.
> 
> In your case, it sounds a bit like an asset problem, so I would rather do this at conversion time.
> Here is how to apply scaling at conversion time:
> https://docs.microsoft.com/en-us/azure/remote-rendering/how-tos/conversion/configure-model-conversion#geometry-parameters
> 
> Cheers,
> Florian

Thank you, I'm quite new to directx in general this is my first real project where I've used it at all. I'll have a look through the documentation, would you recommend looking at any other material for some understanding?

**Comment by FlorianBorn71** [comment] 2020-06-08 12:28
> Yeah, my room has spotty wifi at times so that might have been a factor.

Fwiw, network/Wifi quality should not affect the spin-up times for sessions, because once triggered, it is a process that runs in Azure to install and set up the VM and which reports back when done.

> I'm quite new to directx in general this is my first real project where I've used it at all.

The documentation in Azure Remote Rendering has barely any information on DirectX. In fact, this is (currently) the only DX/C++ sample and it focuses on the integration of ARR, rather than DX itself. But if you want to learn DX, there are great resources out there (I would then prefer to develop on desktop PC rather than HL, just for the turnaround times ;-) )

Most users actually prefer to work with the Unity integration, because many things are so much easier there. For instance UI elements or status text display. For comparison, look at how complicated a simple text status display is when you have to write it from scratch. This native sample is for users who do not shy away from low level DX programming and/or who have a native DX based codebase in place already.

Cheers!

**Comment by werto165** [comment] 2020-06-08 12:53
> > Is it possible to scale the geometry that is being rendered at azure? The model I imported was huge!
> 
> There are basically two options:
> 
> * You can scale the asset at conversion time
> * You can dynamically scale objects at runtime if you apply scaling to the root entity. When you call LoadModel, you can pass a parent entity (it is null in the C++ sample) and if that entity is already scaled, the model will appear scaled right after loading.
> 
> In your case, it sounds a bit like an asset problem, so I would rather do this at conversion time.
> Here is how to apply scaling at conversion time:
> https://docs.microsoft.com/en-us/azure/remote-rendering/how-tos/conversion/configure-model-conversion#geometry-parameters
> 
> Cheers,
> Florian
would this be the usage of positioning the hologram? 
 RR::ApiHandle<RR::Entity> e; 
    Microsoft::Azure::RemoteRendering::Double3 a = { 0, 0, 0 };
    e->Position() = a; 
    params.Parent = e;

**Comment by FlorianBorn71** [comment] 2020-06-08 13:05
Two things:

1) The new entity must be created, rather than being a local variable. Creating a new entity is a member function on the RemoteManager object (RemoteManager::CreateEntity)

2) 
The 'setter' for the position property is currently counter-intuitive, so it should be rather:
e->Position(a);
instead of
e->Position() = a;

(this may be fixed in the future. Personally I prefer when getters and setters in C++ are properly named as GetPosition/SetPosition)

It seems the docs a re locking a paragraph how to create a new entity here:
https://docs.microsoft.com/en-us/azure/remote-rendering/concepts/entities

I will add that doc...

**Comment by FlorianBorn71** [comment] 2020-06-08 18:19
Here is a new docs paragraph with some code how to create a new entity:
https://docs.microsoft.com/en-us/azure/remote-rendering/concepts/entities#create-an-entity

**Comment by werto165** [comment] 2020-06-09 08:27
Thanks that's great! I have tried the sample once more this morning and I can't even run it anymore I'm plagued with the:

Unhandled exception at 0x00007FFF73598E88 (Microsoft.Holographic.HybridRemoting.dll) in HolographicApp.exe: 0xC0000005: Access violation reading location 0x0000000000000000. 

it happens within Windows.graphics.holographic.h 

```
template <typename D> Windows::Foundation::IReference<Windows::Graphics::Holographic::HolographicStereoTransform> consume_Windows_Graphics_Holographic_IHolographicCameraPose<D>::TryGetViewTransform(Windows::Perception::Spatial::SpatialCoordinateSystem const& coordinateSystem) const
{
    Windows::Foundation::IReference<Windows::Graphics::Holographic::HolographicStereoTransform> value{ nullptr };
    check_hresult(WINRT_SHIM(Windows::Graphics::Holographic::IHolographicCameraPose)->TryGetViewTransform(get_abi(coordinateSystem), put_abi(value)));
    return value;
}

```

**Comment by FlorianBorn71** [comment] 2020-06-09 09:16
When does this crash happen? Right at startup (before the display text shows anything)?
When you deploy to HL, can you make sure the device is not in sleeping mode, but rather shows the Pins-panel?

**Comment by werto165** [comment] 2020-06-09 09:39
> When does this crash happen? Right at startup (before the display text shows anything)?
> When you deploy to HL, can you make sure the device is not in sleeping mode, but rather shows the Pins-panel?

It will show the animated hologram that goes around the real world where you start a deployment of an app. So just as it finishes deploying, nothing is shown on the screen, I've tried to step through the code but it goes through a lot of .dll files I assume ( or things I dopn't have the binaries for). The device isn't in sleeping mode it's on the start menu.

**Comment by FlorianBorn71** [comment] 2020-06-17 16:03
Hi,
just to let you know that we are still investigating the crash in Microsoft.Holographic.HybridRemoting.dll.

In the meanwhile I was able to reproduce it a few times and my finding is that having active breakpoints makes it much more likely to happen. Probably because the internal state switches to 'disconnected' when it does not tick for a second and then the code continues to operate on stale objects.
So I recommend running the sample without any breakpoints.

**Comment by FlorianBorn71** [comment] 2020-06-25 15:46
Some news here, we were able to fix this problem and the fix will be in the next release, the one after current 2020-06-24. The timeframe for that release is mid/end of next week.

**Closed** 2020-06-25 15:46 UTC
