### ISSUE TITLE
[Remote rendering problem] RemoteRenderingClient.dll not loading error in unity 2020.3.20f1

### ISSUE THREAD

**Issue by Prithiaga** [Azure/azure-remote-rendering#63] opened 2022-02-13 17:02 UTC
Hello,

I am trying out the remote rendering samples for Unity. But facing the below error in both Quickstart and Tutorial-Complete samples =>

../azure-remote-rendering/Unity/Tutorial-Complete/Library/PackageCache/com.microsoft.azure.remote-rendering@80af63c73f6c-1644766882913/Plugins/x86_64/RemoteRenderingClient.dll', expected x64 architecture, but was Unknown architecture. **You must recompile your plugin for x64 architecture.**
![image](https://user-images.githubusercontent.com/18065954/153765894-555aa01a-c400-40c5-a68a-011d4dce8c19.png)

Environment:
Unity 2020.3.20f1
Azure Remote Rendering package version 1.0.46
Visual Studio 2019 - 16.11.10

Kindly let me know if I am missing something here.

Thank you.

**Comment by Prithiaga** [comment] 2022-02-14 05:24
Update: Azure Remote Rendering package version 1.0.41 works fine.

**Comment by mohammedari** [comment] 2022-02-14 08:03
Same problem occurs in my environment. 1.0.41 works but 1.0.46 fails.

**Comment by FlorianBorn71** [comment] 2022-02-14 11:12
We apologize, because we have published 1.0.46 which had missing/incomplete binaries. 
We have fixed this by releasing 1.0.47, so that version should be fine to upgrade to.

Thanks for raising this issue!

**Comment by FlorianBorn71** [comment] 2022-02-15 13:15
Quick update here. We have found a regression in 1.0.47 when using the OpenXR version (WMR version of 1.0.47 is just fine). 
We are working hard on a fix which will be released with 1.0.48. Until then, we suggest to go back to 1.0.41.
Again, sorry for all the inconveniences with latest release!

**Comment by FlorianBorn71** [comment] 2022-02-21 13:49
Just fyi, Release 1.0.48 is out so it's safe to upgrade.
Florian

**Closed by FlorianBorn71** 2022-02-21 13:49 UTC
Labels: rendering

**Comment by mohammedari** [comment] 2022-02-21 14:28
Thanks Florian!
