### ISSUE TITLE
ARR Showcase App - Failed to load model

### ISSUE THREAD

**Issue by ketankapila2** [Azure/azure-remote-rendering#3] opened 2020-04-12 00:37 UTC
Failed to load model. Reason: Load model failed with status 'FileDownloadFailed'

No errors during asset conversion. Session connected without issues. I ensured the session's region was set to the same as the conversion region.

**Comment by rikogeln** [comment] 2020-04-12 12:02
Can you provide which values you entered for the model? Where did you enter storage account name, blob container name etc. 

If possible  please also provide a sessionID

**Comment by ketankapila2** [comment] 2020-04-12 15:49
Storage account name, key and model container were all entered in the inspector on the RemoteRenderingService object.

Session ID: 4f50d4f5-7677-4201-9e30-92975c15da95

**Comment by ShogoTakagi** [comment] 2020-04-13 01:29
I got same issue with showcase app. It didn't happen on Tutorial 3(use SAS URI).
The XML from the container's URL shows below.
<details>
<summary>container/output/converted.arrAsset</summary>

```pl
<Error>
<Code>ResourceNotFound</Code>
<Message>
The specified resource does not exist. RequestId:--Time:--
</Message>
</Error>
```

</details>
Is this relevant to this issue?

**Comment by sebastianpick** [comment] 2020-04-14 16:27
@ketankapila2 Based on the description I tried to reproduce the issue but without success. Please verify that you specified the correct URI as output by the conversion step and that nothing got lost somehow, e.g., parts of the SAS token (the part after the '?').

What I also noticed when going through all the steps locally is that we are currently outputting the SAS URI twice at the end of the Conversion.ps1 script. Please ensure that you only copy everything from the first 'https://' up to but excluding the second one (and everything that follows). The URI should look something like 'https://<blobstoreaccount>.blob.core.windows.net/<container>/<path_to_file>?<SAS token>'. The 'SAS token' part ends in '&sp=r' for me, which it should also for you. You can verify that all is good by copying the URI to a browser. If you copied 'too much', you should get an authentication failure. If it works, the very same URI should be used in the tutorials.

@ShogoTakagi The 'ResourceNotFound' code in the snippet you posted indicates that something was actually not existing at the searched location. I assume that conversion itself succeeded for you. Please access Azure Portal, go into your storage account, and make sure the file is actually found in the container under the mentioned path.

**Comment by ketankapila2** [comment] 2020-04-14 16:57
@sebastianpick  I converted a model yesterday and did not receive a URI after running the Conversion.ps1 script, though I did receive one upon converting a model a few days ago. I've been manually generating the SAS URI in the Azure Portal and haven't had any issues when viewing with the Quickstart project. I did not see the same SAS URI input field in the inspector for the ARR Showcase project, as I figured it was using a different method for loading the models. The RemoteRenderingService object in the ARR Showcase project has parameters for connecting storage account.

**Comment by ShogoTakagi** [comment] 2020-04-15 05:07
@sebastianpick Yes, I have successfully converted models and have confirmed load in the URI(Tutorial 3).
But in the show-case-app, it succeeds in retrieving the list of models, but no thumbnails are displayed and the download fails.

**Comment by sebastianpick** [comment] 2020-04-15 08:42
@ketankapila2 If you use the Conversion.ps1 script you will have to add '-UseContainerSas' to the command line for it to generate a SAS token for you. If you do not do this, it is absolutely fine to generate a token later manually via the Azure Portal, just as you were already doing. Please note, however, that you should not use your storage account access key here. Also note, that SAS tokens have an inherent expiration date after which you would have to generate a new SAS token.

The Showcase app does in fact load models differently in that it extracts all the models from the storage account you specified. So you do not explicitly specify a URI and therefore can also not provide a SAS token. However, as discovered by @ShogoTakagi, we seem to have an issue when loading models there. I was able to reproduce this locally and am currently looking into it.

@ShogoTakagi, the thumbnail fails to load as the conversion scripts does not add one to the output folder after conversion. If you want you can add one yourself, however. Please use the file path from the load failure message as an indicator where to exactly place it. Basically, there is an identically named PNG file placed right next to the arrAsset file.

**Comment by ketankapila2** [comment] 2020-04-15 15:21
I can confirm I also see the models from the storage container in the arr showcase app UI, but all fail to download upon placement.

My question of the Storage Account Key was regarding the optional Storage Account Settings in the Remote Rendering Service Profile, but I'm assuming I was using the correct Storage Account Key (Storage Account Access Key, not a generated SAS URI for the storage account - though uncertain if that would work too) since the UI displayed the models from the container.

I believe I'm just running into the same issue that you were able to reproduce and are now looking into.

**Comment by sebastianpick** [comment] 2020-04-16 08:49
Concerning the SAS URI: it should never work if you specify the Storage Account Access Key as part of the asset URI. Please always treat that key like a password. If you generate the SAS token via the Azure Portal, the best way is to just copy the full URI from the respective output field and use it as-is in the Unity samples etc.

The Showcase App in its current form does not support loading models via linked storage accounts and it does also not generate or retrieve SAS tokens. Therefore, the only way to load models from a storage account at this time is to set the respective container to use a non-private access level. This can be done by going to the container in Azure Portal, clicking on "Change access level", and changing the level from 'Private' to 'Blob' or 'Container'. Note, however, that this will give anyone  full, unauthorized access to the contained data. Consequently, this should not be done if the container holds confidential information. We will improve the Showcase App to not require this step in one of the next releases. In addition, we will add a sample for how to perform model loading via linked storage accounts. At this time, all samples only support loading via SAS URIs or via public containers (again: no SAS token is required then, but unauthorized access is possible for anyone). For now, please consult the documentation if you would like to try loading via a linked storage account (https://docs.microsoft.com/en-us/azure/remote-rendering/concepts/models#loading-models).

**Comment by ShogoTakagi** [comment] 2020-04-17 05:50
>the only way to load models from a storage account at this time is to set the respective container to use a non-private access level. This can be done by going to the container in Azure Portal, clicking on "Change access level", and changing the level from 'Private' to 'Blob' or 'Container'. 

@sebastianpick 
It works. Thank you!

However, because the connection is so unstable, there are many failed connections to the session, and even when connected, sometime the model can't seen.
If you can't see the model, Network roundtrip is 0.00ms on Stats.
![image](https://user-images.githubusercontent.com/27467669/79535827-895b7980-80b9-11ea-8fac-8f77e6658514.png)

This issue may only occur in region southeasetasia.

**Comment by sebastianpick** [comment] 2020-04-17 08:56
@ShogoTakagi It is great that you are now able to load models! @ketankapila2 If this solution also works for you and is sufficient for now, I would like to close this ticket. The improvements regarding loading models from private containers via the Showcase App and additional samples will be coming in future releases.

@ShogoTakagi Regarding your issue of having bad connections: I would like to ask you to repost your findings (including the screenshot) in a dedicated ticket. This makes it easier for us to track specific issues. Briefly speaking, however, the server seemingly fails to establish a video stream connection.

**Closed** 2020-04-21 11:42 UTC

**Comment by utzy** [comment] 2020-05-26 12:34
@sebastianpick Thanks for your tips above. I have the same error as ShogoTakagi saying **"Load model failed with status 'FileDownloadFailed'"**
Unfortunately setting all my containers to Access Level "Container" does not fix it.
Have you been looking into this a bit more and come up with any new clues on how to fix it?

**Comment by sebastianpick** [comment] 2020-06-10 10:09
@utzy I am sorry for the late reply. We have updated how loading models in the Showcase App works a while ago. Changing the container access level will not work anymore. Instead, you now must link a storage account to your remote rendering account as described here: https://docs.microsoft.com/en-us/azure/remote-rendering/how-tos/create-an-account#link-storage-accounts

In the Showcase App you then specify your remote rendering and storage account data as before.

**Comment by utzy** [comment] 2020-06-16 15:40
@sebastianpick Thanks for the update. I had tried that already in the meantime...unfortunately with no luck...
Still getting the generic error:

`Failed to load model from 'https://teststorage.blob.core.windows.net/arr-output/test.arrAsset'. Reason: Load model failed with status 'FileDownloadFailed'
`
Anything else we might be doing wrong?

I am also slightly astonished that the showcase app has access to read the model names from the storage account and show them. Is "reading filenames" a separate permission from "downloading files"?

**Comment by sebastianpick** [comment] 2020-06-17 09:45
@utzy Could you please tell me around which time you last tried this setup to load a model? Also, did you run the app on device or right from within the Unity Editor? Generally, if all the roles were correctly assigned when linking the storage account (as described in the docs), loading should work.

The showcase app is able to read the filenames from your container because enumerating files and downloading them are realized in distinct ways. Downloading is handled by the API, while file organization (or enumeration) is a responsibility of the app.
The enumeration code in the showcase app uses the public REST API to access storage accounts to compile a list of all assets. That is why it needs all the storage account credentials. If you are interested in the details, you can go to the file arr-showcase-app/Assets/App/Storage/AzureContainerHelper.cs and follow further down from there. For downloading, the app passes the selected blob URL to the remote rendering API. It, in turn, relies on you having linked the used storage account with the used remote rendering account to be able to perform the download.
This is also why the file enumeration might work perfectly while downloading fails.

**Comment by rikogeln** [comment] 2020-06-17 16:52
@utzy To add to what Sebastian said. 
We fixed an issue affecting some arr accounts which prevented us from accessing connected storage accounts. 
To verify that your ARR account works with your storage account 
can you try converting a model using the conversions/create REST API with a connected storage account from the example powershell Conversion.ps1 as outlined in https://docs.microsoft.com/en-us/azure/remote-rendering/samples/powershell-example-scripts#linked-storage-account ? And let us know if this works/fails. If it fails please tell us the conversionId so we can investigate further. 

Sorry for the inconveniences!

**Comment by utzy** [comment] 2020-06-17 18:26
Thanks a lot for your kind assistance guys.
Conversion worked fine and accessing the model via SAS URI worked fine too. Only downloading from conntected container was a problem.

After checking everything twice to no avail, I ended up wiping the repo and setting up everything in Unity from scratch. Fortunately this did the trick.
So sorry that I cannot pin down the error further...maybe some config file that persisted between version updates?
I am just happy it is working now. Keep up the groundbreaking good work :)

**Comment by fermanda** [comment] 2021-06-08 11:16
Hi, sorry if I try to open the discussion once again.
I have a problem in which, I cannot download the file from SAS URI.
With the reason of FileDownloadFailed.

In the other [tutorial example](https://docs.microsoft.com/en-us/azure/remote-rendering/tutorials/unity/tutorial-landing), I was able to load a model from SAS URI.

This is the result from Showcase example
![failed](https://user-images.githubusercontent.com/18476136/121175332-e3a73300-c895-11eb-8ab5-58d89cff8797.png)
