### ISSUE TITLE
[Remote rendering problem] Camera flipped vertically

### ISSUE THREAD

**Issue by WikkidEdd** [Azure/azure-remote-rendering#68] opened 2022-03-29 08:02 UTC
We've noticed occasionally that when starting ARR the camera becomes flipped vertically. It is very rare (maybe 1 in 100) for it to happen and we don't have solid repro steps, but we had a user report that when they connected to ARR that "all content flying around the place, corrupted, messed up" and then they restarted the app and it fixed it. Without knowing exactly what they were seeing it sounds like the possible cause could be the camera being flipped.

We haven't reported it until now as it is so infrequent and there are no solid repro steps, but when our users start reporting it becomes a bit more pressing. 

Can you take a look in to it, please? (Sorry for not being able to provide more information)

**Comment by ChristopherManthei** [comment] 2022-03-29 12:08
Hi @WikkidEdd , sorry for the inconvenience caused by this. We have found the most likely culprit for the issue. It will be fixed with the next release. In the meantime you can apply the following changes to your com.microsoft.azure.remote_rendering package (replace the files in the Runtime folder) to mitigate the uninitialized variable we found:
[com.microsoft.azure.remote_rendering_fix.zip](https://github.com/Azure/azure-remote-rendering/files/8371205/com.microsoft.azure.remote_rendering_fix.zip)

**Comment by WikkidEdd** [comment] 2022-03-29 12:26
🔥 Amazing, even with a poor bug description :)

We'll add this in for our next release

**Comment by ChristopherManthei** [comment] 2022-04-07 12:22
Thanks for sharing this @WikkidEdd ,
The descriptions are in line with what I would expect when this bug appears. The bug already existed on our side for a while now but had never surfaced before. I think the trigger is a new Unity update as we also observed the problem just now using the latest Unity 2020 version. Just out of curiosity, did you perhaps update Unity recently as well?
Cheers,
Christopher

**Comment by WikkidEdd** [comment] 2022-04-07 12:28
Ok, that is good to hear that you think the fix will still work.

No, we're still on Unity 2020.3.19f and we have been for a long time.

**Closed** 2022-04-08 13:56 UTC
Labels: rendering
