### ISSUE TITLE
[Remote rendering problem] Unity issue with reparenting Entities multipe times 

### ISSUE THREAD

**Issue by ujell** [Azure/azure-remote-rendering#112] opened 2023-09-28 16:38 UTC
I am having a weird issue on Unity version while working with a dynamic hiearchy. I first thought it was maybe related with sceneGraphMode parameter while converting the models, but this is reproducable in Showcase app with the default engine model, so I am thinking it might be an ARR bug. 

Explanation: if you move a child Remote Entity Sync Object out of the object hierarchy, move it back to the original parent, and then move an ancestor (except parent) out of the hieararchy, children are not rendered at the original position anymore, despite everything having the same transform values as before. Yes, it is clearly an edge case, however this is actually regularly happening in our app. 

How to reproduce: 
- In Showcase app, add the default engine model to the scene
- Find the engine on the inspector and show children of the RootNode
- You can select any part that you can clearly visually identify, I will use "EngineBlock_Unwrapped_MATRIX_Translation" for this example
- Extend children at least twice
- Enable "Sync Every Frame" parameter on a child (i.e. EngineBlock_Unwrapped) 
<img width="256" alt="Screenshot 2023-09-28 174809" src="https://github.com/Azure/azure-remote-rendering/assets/6547406/9ee36e8c-9b6f-4989-a44a-e1f643ed86ad">

- Reparent EngineBlock_Unwrapped to any other object in the scene, e.g. MixedRealityPlayspace 
<img width="256" alt="Screenshot 2023-09-28 174842" src="https://github.com/Azure/azure-remote-rendering/assets/6547406/54d7cb82-1d80-42e9-ad34-e2297748fac8">

- Move EngineBlock_Unwrapped back to original parent (EngineBlock_Unwrapped_MATRIX_GeometricTranslation). You can disable "Sync Every Frame" or keep it, it does not change the result 
<img width="256" alt="Screenshot 2023-09-28 174858" src="https://github.com/Azure/azure-remote-rendering/assets/6547406/fe463a6f-45a2-41c9-8b55-aa83df8163bb">

- Now repeat this for one of the ancestors besides the direct parent, for instance enable "Sync Every Frame" on "EngineBlock_Unwrapped_MATRIX_Translation" 
<img width="256" alt="Screenshot 2023-09-28 175002" src="https://github.com/Azure/azure-remote-rendering/assets/6547406/c5a30977-3e01-48ac-ac6d-81a2b694316e">

- Then reparent it  to something outside of the hierarchy  e.g. MixedRealityPlayspace. Now it should be displayed at somewhere else 
<img width="256" alt="Screenshot 2023-09-28 174921" src="https://github.com/Azure/azure-remote-rendering/assets/6547406/f805f904-bc0c-43ab-b75e-d7e609e3437c">

- If you move it back to the original parent, it is still at the wrong location 
<img width="256" alt="Screenshot 2023-09-28 174914" src="https://github.com/Azure/azure-remote-rendering/assets/6547406/8faf23b5-c36c-408e-b245-ff7b9f5b44dd"> 

In our models, parents usually have multiple children and seems like all children are affected from this, it behaves like we have moved the parent transform. This issue is not happening if you move the parent directly to somewhere else, or if you move the direct parent instead of the other ancestors. Transform values seems not the be reason, they are the same in all cases as far as I can see. Also this seems to be still happenning if you manually sync after every move instead of using "Sync Every Frame". 

Tested in both in Showcase app as its current state in the repository, as well as with Unity 2021.3.27f1 and ARR 1.2.8 release. 

This is a weird case, so I hope it the explanation is clear enough. Any ideas what this might be? Maybe I am missing a limitation or some documentation? Thanks in advance!

**Comment by ChristopherManthei** [comment] 2023-09-29 15:46
Hi @ujell ,
Sorry for the late reply. Thank you for the detailed repro steps. We haven't finished investigating yet, but we will definitely get back to you next week.
Cheers,
Christopher

**Comment by jumeder** [comment] 2023-10-06 16:26
Hi @ujell, we can reproduce the issue and it looks like a bug on our side. We logged an internal bug ticket with the team and we'll let you know once a fix is available.

**Comment by jumeder** [comment] 2023-11-27 10:56
Hi @ujell, we deployed a fix for this issue in the meantime. While we generally recommend using the latest client version, it also should work with the one you're already using. Let us know if you still run into problems!

**Closed** 2023-12-07 14:29 UTC
Labels: rendering
