### ISSUE TITLE
[Question] - about model conversion

### ISSUE THREAD

**Issue by LeGrandMAG** [Azure/azure-remote-rendering#97] opened 2023-03-03 00:43 UTC
I am currently trying to use Azure's remote rendering tools. And my model is about 580MB (it's an FBX file). I attempted to convert it into arrAsset but it say: "the conversion process exceeded system resources. It's possible the asset is too large.", even though I am using the premium and not the standard performance VM.

Does anyone know the maximum size the 3d model should have so that it is converted successfully ?

(Also, I would be glad to hear some tips about how to reduce the size of my FBX file)

Thank you in advance

**Comment by WikkidEdd** [comment] 2023-03-03 08:33
I could give you tips on how to reduce the size of an FBX files, but the point of ARR is that you don't need to :) ARR can comfortably handle much bigger files than that.

We've had this error before on a file of only 145mb. We didn't report it as an issue at the time, but in hindsight, we should have. We hypothesized that it was the fact that it was a 3.5m triangle model but it was very small and it was causing some problems with the processing. It was a building floor plan with furniture and things like that, but the scale it was exported at was about 20cm. So there were chairs with 45k tris which were about 3mm across.

It could be that it is some other quirk about the file causing the problem, but it might be worth checking the scale of your fbx is sane and trying again.

For the ARR team. I just ran the problem file again to get you a conversion ID (413c019f-bbf6-4d22-b8e5-b8e8732bf47c). One thing I noticed is that the file took a long time to fail. Normally a similar complexity file would convert in under 5 mins, but this took 38 mins before it failed like it was stuck in a loop until it ran out of resources.

**Comment by ChristopherManthei** [comment] 2023-03-03 18:30
Hi @LeGrandMAG ,
Sorry to hear you are having problems. Models can increase in size during the conversion process. However, given the small size of your input data, the problem is probably a bug in our conversion service.

If you are able to share the input data with us, we can debug the problem further and work an a fix. To make sure all privacy concerns are met, please only share models by creating a support request via the [Help + support](https://ms.portal.azure.com/#view/Microsoft_Azure_Support/HelpAndSupportBlade/~/overview) page in the Azure portal.

Cheers,
Christopher

**Comment by LeGrandMAG** [comment] 2023-03-04 03:35
@ChristopherManthei @WikkidEdd, Thank you so much for all the tips and the support. 

I will check the scale of my model again and try again. Also I will create a support request as suggested.

Big thanks

**Comment by LeGrandMAG** [comment] 2023-03-06 00:09
@ChristopherManthei ,  I created a support request and I shared the problematic fbx file there.

Thank you

**Comment by LeGrandMAG** [comment] 2023-03-06 00:12
@ChristopherManthei , I created the support request (support request  ID 2303030050000185). But for some reason I can only upload file as big as 4MB, not more. I won't be able to uploading my model there.

Will there be another way to share my input data with you ?

**Comment by ChristopherManthei** [comment] 2023-03-06 16:55
@LeGrandMAG it looks like you managed to upload the model. Anything below 2gig shouldn't be a problem to upload.

@LeGrandMAG , @WikkidEdd  thank you for providing the models, we can reproduce the issue and will keep you updated with our progress on creating a fix.

**Comment by LeGrandMAG** [comment] 2023-03-06 22:11
@ChristopherManthei Thank you so much for the suppport.

**Comment by FlorianBorn71** [comment] 2023-03-17 10:38
Hi @LeGrandMAG ,
we have deployed a conversion service update that fixes this specific out-of-memory issue. Thanks a lot for your contribution in CSS!
@WikkidEdd , 'your' gltf bug is also understood, but the fix was a bit more involved. It's currently in review and once greenlit, the fix will be part of an upcoming release. I'll keep you updated in a separate channel, so I can close this thread with the original issue.

**Closed** 2023-03-17 10:39 UTC
